import Head from 'next/head'
import Essays from '../../components/work/Essays'




export default function EssaysPage() {
  return (
    <>
      <Head>
        <title>BEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Essays />
    </>
  )
}