import Head from 'next/head'
import Poetry from '../../components/work/Poetry'




export default function PoetryPage() {
  return (
    <>
      <Head>
        <title>BEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Poetry />
    </>
  )
}