import Head from "next/head";
import Navbar from "../components/navbar/Navbar";

const Layout = ({ children }) => {
  return (
    <>
     <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@300;500&family=Arvo:wght@400;700&family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,700&family=DM+Serif+Text:ital@0;1&family=Gloria+Hallelujah&family=Montserrat:wght@300;400;500&family=Noto+Serif+JP:wght@200;300&family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,700;1,800&family=Prompt:wght@200&display=swap" rel="stylesheet"/>
        <title>Ben Schroeder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar />
      <main>{children}</main>
    </>
  );
};

export default Layout;
