import Head from 'next/head'
import Bio from '../../components/about/Bio'




export default function BioPage() {
  return (
    <>
      <Head>
        <title>BEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Bio />
    </>
  )
}