import Head from 'next/head'
import Contact from '../components/Contact'




export default function ContactPage() {
  return (
    <>
      <Head>
        <title>BEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Contact />
    </>
  )
}