import Head from 'next/head'





export default function Home() {
  return (
    <>
      <Head>
        <title>BEN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <h1 class="text-3xl font-bold underline p-100">
    Hello world!
  </h1>
      </Head>
     
    </>
  )
}
